resolver: lts-9.14

packages:
- .

extra-deps:
  - grapefruit-examples-0.1.0.7
  - grapefruit-frp-0.1.0.7
  - grapefruit-ui-0.1.0.7
  - grapefruit-ui-gtk-0.1.0.7
  - arrows-0.4.4.1
  - fraction-0.1.0.6
  - grapefruit-records-0.1.0.7
  - Stream-0.4.7.2
  - lazysmallcheck-0.6

flags: {}

extra-package-dbs: []
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]

nix:
    enable: true
    pure: true
    packages:
    - ncurses
    - pkgconfig
    - gnome3.gtk
    - xorg.libX11
    - xorg.xproto
